import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import pluginVue from 'eslint-plugin-vue';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
  globalIgnores(['**/dist/', '**/coverage/', '**/.data/', '.pnpm-store/', 'local/']),
  js.configs.recommended,
  tseslint.configs.strict,
  pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser, extraFileExtensions: ['.vue'] },
    },
    rules: {
      'vue/multi-word-component-names': ['error', { ignores: ['App'] }],
    },
  },
  {
    // Generated by the shadcn-vue CLI and kept close to upstream (see packages/ui/README.md).
    files: ['packages/ui/src/components/**'],
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
    },
  },
  {
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ['apps/web/**', 'packages/ui/**', 'packages/web-plugin-api/**', 'plugins/*/src/web/**'],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Built-in modules must prove that the public packages are enough to write a plugin.
    files: ['plugins/**/*.{ts,vue}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/apps/**',
                '@outpost/server',
                '@outpost/server/*',
                '@outpost/web',
                '@outpost/web/*',
              ],
              message:
                'Plugins may only import public packages: @outpost/plugin-api, @outpost/web-plugin-api, @outpost/shared, @outpost/ui.',
            },
          ],
        },
      ],
    },
  },
  prettier,
);
